version: "3.9"
volumes:
  Worlds:
  Logs:
services:
  bdscore:
    container_name: bds_maneger_core
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - Worlds:/data/worlds
      - Logs:/data/logs
    environment:
      DESCRIPTION: "Docker Test"
      WORLD_NAME: "Docker Run Test"
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      XBOX_ACCOUNT: "false"
      PLAYERS: "5"
      BDS_VERSION: "latest"
      SERVER: "bedrock"
      CRON_BACKUP: "*/1 * * * *"
    ports:
      - 3000:3000/tcp
      - 19132:19132/udp
      - 19133:19133/udp