name: Publish image (Release)
on:
  release:
    types:
      - created

env:
  DOCKERPLATFORM: "linux/amd64,linux/arm64,linux/arm/v7"
  DOCKERIMAGE: "ghcr.io/the-bds-maneger/container"

jobs:
  publishRelease:
    runs-on: ubuntu-latest
    name: Publish image
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v2

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login into registry Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get package version"
        run: echo "PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Build and Push image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERIMAGE }}:${{ env.PACKAGE_VERSION }}
          platforms: ${{ env.DOCKERPLATFORM }}
          cache-from: type=gha,scope=${{ github.ref }}_${{ github.repo }}
          cache-to: type=gha,mode=max,scope=${{ github.ref }}_${{ github.repo }}
